seafile:
  image: m3adow/seafile:dev
  env_file:
  - ./secrets.env
  #volumes:
  #  - cloud-data2:/seafile
  external_links:
  - 'galera/galera-lb:mysql-server'
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always

debugger:
  image: m3adow/nettools
  env_file:
  - ./secrets.env
  #volumes:
  #  - cloud-data:/seafile
  volume_driver: convoy-gluster
  external_links:
  - 'galera/galera-lb:mysql-server'
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
