seafile:
  image: m3adow/seafile:dev
  env_file:
  - ./secrets.env
  labels:
    io.rancher.sidekicks: seafile-setup, debugger
    io.rancher.container.pull_image: always
  volumes_from:
  - seafile-setup
  command: run_only

seafile-setup:
  image: m3adow/seafile:dev
  env_file:
  - ./secrets.env
  volumes:
  - /seafile
  labels: 
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: true
  command: setup_only

seafile-db:
  image: mariadb:latest
  env_file:
  - ./secrets.env
  labels:
    io.rancher.container.pull_image: always
debugger:
  image: m3adow/nettools
  env_file:
  - ./secrets.env
  volumes_from:
  - seafile-setup
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
