seafile-setup:
  image: m3adow/seafile:dev
  env_file:
  - ./secrets.env
  external_links:
  - 'galera/galera-lb:mysql-server'
  volumes:
  - /seafile
  labels: 
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: true
  command: setup_only

seafile:
  image: m3adow/seafile:dev
  env_file:
  - ./secrets.env
  external_links:
  - 'galera/galera-lb:mysql-server'
  labels:
    io.rancher.sidekicks: seafile-setup, debugger
    io.rancher.container.pull_image: always
  volumes_from:
  - seafile-setup
  command: run_only
  
debugger:
  image: m3adow/nettools
  env_file:
  - ./secrets.env
  volumes_from:
  - seafile-setup
  external_links:
  - 'galera/galera-lb:mysql-server'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
